### PR TITLE
fix: Out of bounds reference on non-compliant SCSI VPD responses

### LINKED ISSUE #119: [Bug] tcgdiskstat - `runtime error: index out of range [3] with length 1`
I can observe a panic when using `tcgdiskstat` on SCSI devices (/dev/sdX). That mostly happens with USB-Sticks or SATA-to-USB adapter that are connected to the PC, when the command is executed.

This is an inconvenience, as the devices can be unplugged and my tested devices did not support SSC anyhow.

However, investigation into the panic shows that this is triggered by sub-optimal code inside the `sgio.SCSIInquiry()`function. That handles the responses of the device messages.

**Error Message**
```
sudo <HOME>/go/bin/tcgdiskstat
panic: runtime error: index out of range [3] with length 1

goroutine 1 [running]:
github.com/open-source-firmware/go-tcg-storage/pkg/drive/sgio.SCSIInquiry(0x6)
        <HOME>/go/pkg/mod/github.com/open-source-firmware/go-tcg-storage@v0.8.22-0.20230920111945-87417253ae2d/pkg/drive/sgio/ops.go:177 +0x64b
github.com/open-source-firmware/go-tcg-storage/pkg/drive.isSCSI({0x8de298?, 0xc000062258?})
        <HOME>/go/pkg/mod/github.com/open-source-firmware/go-tcg-storage@v0.8.22-0.20230920111945-87417253ae2d/pkg/drive/scsi_nix.go:90 +0x27
github.com/open-source-firmware/go-tcg-storage/pkg/drive.Open({0xc0000135c0?, 0xc0000f9d90?})
        <HOME>/go/pkg/mod/github.com/open-source-firmware/go-tcg-storage@v0.8.22-0.20230920111945-87417253ae2d/pkg/drive/drive_nix.go:19 +0x65
github.com/open-source-firmware/go-tcg-storage/pkg/core.NewCore({0xc0000135c0, 0x8})
        <HOME>/go/pkg/mod/github.com/open-source-firmware/go-tcg-storage@v0.8.22-0.20230920111945-87417253ae2d/pkg/core/dev.go:22 +0x27
main.main()
        <HOME>/go/pkg/mod/github.com/open-source-firmware/go-tcg-storage@v0.8.22-0.20230920111945-87417253ae2d/cmd/tcgdiskstat/main.go:65 +0x3e8

```

* In case of one device (Sharkoon branded USB-Stick) the device would answer to the VPD request without raising an error but the message was wrong/incomplete. Leading to the shown panic inside the device information querry.
* Another device - can't find it anymore - would already panic when parsing the serial number response.

I see two main problems here:
1. The code should generally be more defensive when accessing the returned data and check bounds and expected values. Eg. the length and the page code of the response.
2. To be extra careful the VPD page 0x00 should be queried to ensure the relevant pages are supported/implemented by the device.

Note: That page itself may not be present in very old devices. In that case the code should probably fail/stop gracefully.

### PR DESCRIPTION
**Pull request by mynetz**
Fix behavior of SCSIInquiry() on misbehaving SATA devices.

This commit fixes the handling of VPD responses that may be bogus or incomplete.

Some devices do not seem to implement the VPD pages, have wrong or broken answers. This fix ensure the response to the query have the expected page in the response and the correct size.

During testing several USB sticks and USB-to-SATA adapter showed wrong answers in the serial number or device identification page.

The fix changes the workflow to first querry the device for supported VPD pages and only if implemented requests the relevant VPD page.

Changes in detail:
* Introduce additional constants for easier readability
* Genric structure for VPD header responses
* Ensure the standard SCSI_INQUIRY has the minimal expected length
* Check for supported VPD pages
* Fix offset error for serial number size
* Fix length check when iterating through the id descriptor list
* Add check for assiciation field as the validity of the protocol field also depends on this according to SPC-3

Fixes #119

### CODE REVIEW

File: pkg/drive/sgio/ops.go [hunk 1]
```diff
@@ -28,12 +28,19 @@ const (
...
 	SCSI_MODE_SENSE_6     = 0x1a
 	SCSI_READ_CAPACITY_10 = 0x25
 	SCSI_ATA_PASSTHRU_16  = 0x85
 	SCSI_SECURITY_IN      = 0xa2
 	SCSI_SECURITY_OUT     = 0xb5
+
+	SCSI_INQUIRY            = 0x12
+	SCSI_INQUIRY_STD_LENGTH = 0x24 // expected minimal length of SCSI_INQUERY according to SPC-3 (and newer)
+
+	SCSI_VPD_STD_LENGTH = 0xFF // max page size - should be enoough for most VPDs
```
Comment (ChriMarMe) [inline pkg/drive/sgio/ops.go:40]: nit: spelling `enough` <> `enoough`

File: pkg/drive/sgio/ops.go [hunk 2]
```diff
@@ -128,59 +148,108 @@ func SCSIInquiry(fd uintptr) (*InquiryResponse, error) {
...
 	}
 
-	respBuf = make([]byte, 128)
-	cdb = CDB6{SCSI_INQUIRY}
-	cdb[1] = 0x1 /* Request VPD page 0x80 for serial number */
-	cdb[2] = 0x80
+	/* fixup length field to indicate full page length */
+	l := inqHdr.Length + 5
+	if l < SCSI_INQUIRY_STD_LENGTH {
+		return nil, fmt.Errorf("unexpected respsonse length of SCSI_INQUIRY (%d < %d)", l, SCSI_INQUIRY_STD_LENGTH)
```
Comment (ChriMarMe) [inline pkg/drive/sgio/ops.go:165]: If you create an error with this message in the package instead and use this, one can write tests and check on this specific error.

File: pkg/drive/sgio/ops.go [hunk 3]
```diff
@@ -113,11 +127,17 @@ func (id IdentifyDeviceResponse) String() string {
...
 }
 
-// INQUIRY - Returns parsed inquiry data.
+/*
+	 INQUIRY - Returns parsed inquiry data.
+		- request standard inquiry first
+		- check supported VPDs
+		- query for serial number, if page 0x80 is supported
+	    - query for protocol type, if page 0x83 is supported
+*/
```
Comment (ChriMarMe) [inline pkg/drive/sgio/ops.go:136]: Not sure if multi line comments `/**/` are good practice. Most of the time I see the use of `//`, but its a nit. Decide for yourself :)

File: pkg/drive/sgio/ops.go [hunk 4]
```diff
@@ -128,59 +148,108 @@ func SCSIInquiry(fd uintptr) (*InquiryResponse, error) {
...
+
+		didlen := binary.BigEndian.Uint16(respBuf[2:4]) + 4 // page length (n-3)
+		if (respBuf[1] == SCSI_VPD_PAGE_DI) && (didlen > 4) && (didlen <= 2048) {
+			/* Device Identification VPD page - decode length and descriptor list */
+
+			did := respBuf[4:didlen] // identification descriptor list (full)
+
+			/* We are only interested in the protocol identifier.
+			   Loop through all ID descriptors and check for a valid protocol field.
+			*/
```
Comment (ChriMarMe) [inline pkg/drive/sgio/ops.go:237]: Same thing about multi line comments, just a nit, decide for yourself :)

File: pkg/drive/sgio/ops.go (hunk 2 above)
Comment (mynetz) [reply pkg/drive/sgio/ops.go:165]: Yes, @sylv-io also suggested this. Should do it. Was my noob knowledge of Golang doing.. However, if we want testability, there is a lot more to do here. Especially in this function. As it does more than "inquiry". Which would only be the first device interaction.
Nevertheless, the error message/type change is good. Will do.

File: pkg/drive/sgio/ops.go (hunk 3 above)
Comment (mynetz) [reply pkg/drive/sgio/ops.go:136]: I am fine with changing this. Saw both used and same with the above, my C muscle memory kicked in ;)

**Review by ChriMarMe — APPROVED** [review]
